apiVersion: v1
kind: Secret
metadata:
  name: graemebucket
type: Opaque
data:
  S3_BUCKET_ARN: MDAwMAo=
  S3_BUCKET_BUCKET_DOMAIN_NAME: MDAwMAo=
  S3_BUCKET_BUCKET_REGIONAL_DOMAIN_NAME: MDAwMAo=
  S3_BUCKET_HOSTED_ZONE_ID: MDAwMAo=
  S3_BUCKET_ID: MDAwMAo=
  S3_BUCKET_REGION: MDAwMAo=
